### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by mackenziedg** [acastrops/DSR_Project1#1]
I figured it would be easier to discuss the project ideas here instead of having a bunch of commits.

I have a few datasets that I've randomly collected and done some analysis of:

- National campaign expenditures from about 2005-ish, has about 8 million entries of who spent how much to whom when for what. I've already broken it down by state/committee, so that would be a relatively easy thing to implement (ie click on a state or enter a campaign and it'll tell you their spending breakdown?)

- H1B visa breakdown. So like, which companies hire h1b workers, what they're paid, how long they've worked etc.

- A bunch of data about the fruit fly genome.

- Causes of death in the US with about 26 million entries and demographic data etc.

I'm definitely open to other things though, but I figured I would share what I've already looked at.

**Comment by acastrops** [comment]
Can you post your sources for the H1B visa data?

**Comment by mackenziedg** [comment]
I got the data I have from [kaggle](https://www.kaggle.com/nsharan/h-1b-visa), but I'm looking to see if we could get the data from before 2011 as well. I've only found 2002-2007, but am still looking for 2008-2010.

**Comment by mackenziedg** [comment]
I shared the raw data with you all. I'll go ahead and close this.
